-
  point: [1045, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 20, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 500, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [545, 500, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [545, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False