-
  point: [1045, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 100, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 200, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1045, 500, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False