-
  point: [1045, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [900, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [545, 0, -30]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False