-
  point: [0, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [200, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [500, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False