-
  point: [0, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [10, 10, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 20, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [-10, 10, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False