-
  point: [1050, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [50, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [50, 100, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1050, 100, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False