-
  point: [0, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 10, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 10, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 20, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 20, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 30, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 30, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 40, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 40, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 50, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 50, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 60, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [100, 60, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False