-
  point: [0, 0, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 100, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 100, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 200, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 200, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 300, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 300, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 400, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 400, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 500, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 500, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 600, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 600, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [0, 700, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1000, 700, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
