-
  point: [1046, 91.5, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [49.8, 4.4, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [41.1, 104, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1037.7, 191.1, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1028.6, 290.8, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [32.4, 203.6, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [23.7, 303.2, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1019.9, 390.4, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1011.1, 490, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [14.9, 402.8, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [6.2, 502.5, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
-
  point: [1002.4, 589.6, -10]
  max_forward_speed: 1.0
  heading: 0
  use_fixed_heading: False
# -
#   point: [1050, 600, -10]
#   max_forward_speed: 1.0
#   heading: 0
#   use_fixed_heading: False
