<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<!-- Oberon-7P Parallel Gripper (inspired on the Orion 7P Schilling Robotics Manipulator) -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="use_mesh_file" value="false" />
    <xacro:property name="mass_gripper" value="3.96" /> <!-- mass of Gripper (kg) - 54kg*0,001422/0,019395 = 3,96 kg -->
    <xacro:property name="gripper_effort" value="200" />
    <xacro:property name="gripper_velocity" value="15" />
    <!-- Properties for the base of the parallel gripper -->
    <xacro:property name="gripper_base_mesh" value="file://$(find oberon_description)/meshes/grippers/parallel/oberon_gripper_base"/>
    <xacro:property name="gripper_base_x" value="0.12"/>
    <xacro:property name="gripper_base_y" value="0.12"/>
    <xacro:property name="gripper_base_z" value="0.057"/>
    <xacro:property name="gripper_base_volume" value="${gripper_base_x*gripper_base_y*gripper_base_z}"/>

    <!-- Properties for the finger -->
    <xacro:property name="gripper_finger_mesh" value="file://$(find oberon_description)/meshes/grippers/parallel/oberon_finger"/>
    <xacro:property name="gripper_finger_x" value="0.10"/>
    <xacro:property name="gripper_finger_y" value="0.02"/>
    <xacro:property name="gripper_finger_z" value="0.05"/>
    <xacro:property name="gripper_finger_volume" value="${gripper_finger_x*gripper_finger_y*gripper_finger_z}"/>

    <!-- Properties of the tip -->
    <xacro:property name="gripper_tip_mesh" value="file://$(find oberon_description)/meshes/grippers/parallel/oberon_tip"/>
    <xacro:property name="gripper_tip_x" value="0.04"/>
    <xacro:property name="gripper_tip_y" value="0.1"/>
    <xacro:property name="gripper_tip_z" value="0.079999"/>
    <xacro:property name="gripper_tip_volume" value="${gripper_tip_x*gripper_tip_y*gripper_tip_z}"/>

    <!-- Properties of the tip holder -->
    <xacro:property name="gripper_tip_holder_mesh" value="file://$(find oberon_description)/meshes/grippers/parallel/oberon_tip_holder"/>
    <xacro:property name="gripper_tip_holder_x" value="0.139499"/>
    <xacro:property name="gripper_tip_holder_y" value="0.01"/>
    <xacro:property name="gripper_tip_holder_z" value="0.004"/>
    <xacro:property name="gripper_tip_holder_volume" value="${gripper_tip_x*gripper_tip_y*gripper_tip_z}"/>

    <!-- Total volume -->
    <xacro:property name="gripper_total_volume" value="${gripper_base_volume +
                                                         2*gripper_finger_volume +
                                                         2*gripper_tip_volume +
                                                         2*gripper_tip_holder_volume}"/>

    <xacro:macro name="gripper_link" params="mass x y z mesh *origin">
        <inertial>
            <xacro:insert_block name="origin" />
            <mass value="${mass}"/>
            <inertia ixx="${0.083333333 * mass * (y*y + z*z)}"
                     iyy="${0.083333333 * mass * (x*x + z*z)}"
                     izz="${0.083333333 * mass * (x*x + y*y)}"
                     ixy="0.0"
                     ixz="0.0"
                     iyz="0.0"
            />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${mesh}.dae" scale="1 1 1"/>
            </geometry>
        </visual>

        <collision>
          <xacro:if value="${use_mesh_file}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${mesh}.stl" scale="1 1 1"/>
            </geometry>
          </xacro:if>
          <xacro:unless value="${use_mesh_file}">
            <xacro:insert_block name="origin" />
            <geometry>
                <box size="${x} ${y} ${z}" />
            </geometry>
          </xacro:unless>
        </collision>
    </xacro:macro>

    <xacro:macro name="parallel_gripper" params="namespace parent">
        <!-- Gripper base -->
        <link name="${namespace}/base_gripper">
            <xacro:gripper_link mass="${mass_gripper * gripper_finger_volume / gripper_total_volume}"
                                x="${gripper_base_x}"
                                y="${gripper_base_y}"
                                z="${gripper_base_z}"
                                mesh="${gripper_base_mesh}">
                <origin xyz="0 0 ${gripper_base_z*0.5}" rpy="0 0 0"/>
            </xacro:gripper_link>
        </link>

        <joint name="${namespace}/end_effector_anchor_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${namespace}/base_gripper"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 ${pi*0.5} 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <gazebo reference="${namespace}/base_gripper">
            <selfCollide>false</selfCollide>
        </gazebo>

        <!-- ****************************************************************************************************** -->
        <!-- Left finger -->
        <link name="${namespace}/finger_left">
            <xacro:gripper_link mass="${mass_gripper * gripper_base_volume / gripper_total_volume}"
                                x="${gripper_finger_x}"
                                y="${gripper_finger_y}"
                                z="${gripper_finger_z}"
                                mesh="${gripper_finger_mesh}">
                <origin xyz="0.05 -0.01 0.0" rpy="0 0 0"/>
            </xacro:gripper_link>
        </link>

        <joint name="${namespace}/finger_left_joint" type="revolute">
            <parent link="${namespace}/base_gripper"/>
            <child link="${namespace}/finger_left"/>
            <origin xyz="0.0 -0.028 0.05" rpy="0 ${-pi*0.5} 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="${gripper_effort}" lower="${-pi*0.3333}" upper="0" velocity="${gripper_velocity}"/>
            <dynamics damping="5" friction="10"/>
        </joint>

        <xacro:simple_transmission joint="${namespace}/finger_left_joint"/>

        <gazebo reference="${namespace}/finger_left">
          <selfCollide>true</selfCollide>
          <kp>1000000.0</kp>
          <kd>1.0</kd>
          <mu1>1.0</mu1>
          <mu2>1.0</mu2>
          <minDepth>0.001</minDepth>
          <maxContacts>3</maxContacts>
          <implicitSpringDamper>1</implicitSpringDamper>
      </gazebo>

        <!-- ****************************************************************************************************** -->
        <!-- Left finger tip -->
        <link name="${namespace}/finger_tip_left">
            <xacro:gripper_link mass="${mass_gripper * gripper_tip_volume / gripper_total_volume}"
                                x="${gripper_tip_x}"
                                y="${gripper_tip_y}"
                                z="${gripper_tip_z}"
                                mesh="${gripper_tip_mesh}">
                <origin xyz="0.015 -0.035 0.0" rpy="0 0 0"/>
            </xacro:gripper_link>
        </link>

        <joint name="${namespace}/finger_tip_left_joint" type="revolute">
            <parent link="${namespace}/finger_left"/>
            <child link="${namespace}/finger_tip_left"/>
            <origin xyz="0.118 -0.009 0.0" rpy="0 0 ${0.5*pi}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${gripper_effort}" lower="0" upper="0" velocity="${gripper_velocity}"/>
            <dynamics damping="5" friction="10"/>
        </joint>

        <xacro:simple_transmission joint="${namespace}/finger_tip_left_joint"/>

        <gazebo reference="${namespace}/finger_tip_left">
            <selfCollide>true</selfCollide>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <minDepth>0.001</minDepth>
            <maxContacts>3</maxContacts>
            <implicitSpringDamper>1</implicitSpringDamper>
        </gazebo>

        <!-- ****************************************************************************************************** -->
        <!-- Right finger -->
        <link name="${namespace}/finger_right">
            <xacro:gripper_link mass="${mass_gripper * gripper_base_volume / gripper_total_volume}"
                                x="${gripper_finger_x}"
                                y="${gripper_finger_y}"
                                z="${gripper_finger_z}"
                                mesh="${gripper_finger_mesh}">
                <origin xyz="0.05 -0.01 0.0" rpy="0 0 0"/>
            </xacro:gripper_link>
        </link>

        <joint name="${namespace}/finger_right_joint" type="revolute">
            <parent link="${namespace}/base_gripper"/>
            <child link="${namespace}/finger_right"/>
            <origin xyz="0.0 0.028 0.05" rpy="0 ${-pi*0.5} ${pi}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${gripper_effort}" lower="${-pi*0.3333}" upper="0" velocity="${gripper_velocity}"/>
            <dynamics damping="5" friction="10"/>
        </joint>

        <xacro:simple_transmission joint="${namespace}/finger_right_joint"/>

        <gazebo reference="${namespace}/finger_right">
            <selfCollide>true</selfCollide>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <minDepth>0.001</minDepth>
            <maxContacts>3</maxContacts>
            <implicitSpringDamper>1</implicitSpringDamper>
        </gazebo>

        <!-- ****************************************************************************************************** -->
        <!-- Right finger tip -->
        <link name="${namespace}/finger_tip_right">
            <xacro:gripper_link mass="${mass_gripper * gripper_tip_volume / gripper_total_volume}"
                                x="${gripper_tip_x}"
                                y="${gripper_tip_y}"
                                z="${gripper_tip_z}"
                                mesh="${gripper_tip_mesh}">
                <origin xyz="0.015 -0.035 0.0" rpy="0 0 0"/>
            </xacro:gripper_link>
        </link>

        <joint name="${namespace}/finger_tip_right_joint" type="revolute">
            <parent link="${namespace}/finger_right"/>
            <child link="${namespace}/finger_tip_right"/>
            <origin xyz="0.118 -0.009 0.0" rpy="0 0 ${0.5*pi}"/>
            <axis xyz="0 0 1"/>
            <limit effort="${gripper_effort}" lower="0" upper="0" velocity="${gripper_velocity}"/>
            <dynamics damping="5" friction="10"/>
        </joint>

        <xacro:simple_transmission joint="${namespace}/finger_tip_right_joint"/>

        <gazebo reference="${namespace}/finger_tip_right">
          <selfCollide>true</selfCollide>
          <kp>1000000.0</kp>
          <kd>1.0</kd>
          <mu1>1.0</mu1>
          <mu2>1.0</mu2>
          <minDepth>0.001</minDepth>
          <maxContacts>3</maxContacts>
          <implicitSpringDamper>1</implicitSpringDamper>
      </gazebo>

    </xacro:macro>
</robot>
